version: '3.7'

services:

  database:
    hostname: database
    restart: unless-stopped
    env_file:
      - server/.env
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - aei_erp_network

  server:
    hostname: server
    restart: unless-stopped
    env_file:
      - server/.env
    build:
      context: ./server 
      dockerfile: Dockerfile.server 
    ports:
      - ${PORT}:5000
    depends_on:
      - database
    networks:
      - aei_erp_network

  app:
    hostname: app
    restart: unless-stopped
    env_file:
      - app/.env
    build:
      context: ./app 
      dockerfile: Dockerfile.app 
    ports:
      - ${VITE_APP_PORT}:80
    depends_on:
      - server
    networks:
      - aei_erp_network