/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    ExpandedSidebar: typeof import('./src/components/sidebar/ExpandedSidebar.vue')['default']
    ExtendedSidebar: typeof import('./src/components/sidebar/ExtendedSidebar.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Icons: typeof import('./src/components/Icons.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    MaterialSymbolIcon: typeof import('./src/components/MaterialSymbolIcon.vue')['default']
    ReducedSidebar: typeof import('./src/components/sidebar/ReducedSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Sidebar/Search.vue')['default']
    SearchSidebar: typeof import('./src/components/sidebar/SearchSidebar.vue')['default']
    Sidear: typeof import('./src/components/sidebar/Sidear.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SideBar: typeof import('./src/components/Sidebar/SideBar.vue')['default']
  }
}
