#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "\033[1m[Husky] 🚫 Pre-commit hook [main branch]\033[0m"
  echo
  echo "🛑 Pas de commit directement sur la branche main !"
  echo "👉 Merci de créer une branche et de faire une pull request"
  echo
  exit 1
fi

npx lint-staged
