name: Build infrastructure with .env.example

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Renommer .env en .env.example
      run: mv .env .env.example

    - name: Lancer Docker Compose
      run: docker-compose up -d --build
